# Generated by Django 4.2.2 on 2023-07-10 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опублікувати Категорію')),
                ('recommended', models.BooleanField(default=False, verbose_name='Рекомендувати Категорію')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='upload/products/images/%Y/%m/%d/')),
                ('description', models.TextField(blank=True, max_length=5000, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('price_last', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('recommended', models.BooleanField(default=False, verbose_name='Рекомендувати товар')),
                ('quantity', models.PositiveIntegerField()),
                ('is_published', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='app_product.category')),
            ],
        ),
    ]
