# Generated by Django 4.2.2 on 2023-07-25 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0002_rename_name_category_title_remove_product_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categories',
            new_name='category',
        ),
    ]
