# Generated by Django 4.2.2 on 2023-07-25 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0004_rename_category_categories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
    ]
